version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t ministryofjustice/helloworld-dstest:$TAG .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push ministryofjustice/helloworld-dstest:$TAG
